# Default SOPS config: use age by default; optional KMS via env
creation_rules:
  - path_regex: ".*\\.sops$"
    # Age recipient: replace or generate via `age-keygen -y -o age.key`
    # Use env var SOPS_AGE_RECIPIENTS to override
    age: ${SOPS_AGE_RECIPIENTS}
    # Optional KMS (AWS) can be enabled by setting SOPS_AWS_KMS_ARN
    kms: ${SOPS_AWS_KMS_ARN}
    # Optional GCP KMS
    gcp_kms: ${SOPS_GCP_KMS_RESOURCE_ID}
    # Optional Azure Key Vault
    azure_keyvault: ${SOPS_AZURE_KEY_VAULT}
