# SOPS config: default to AGE; allow optional cloud KMS via env
# See https://github.com/getsops/sops#usage for env variable semantics
creation_rules:
  - path_regex: ".*\\.sops$"
    # Provide recipients via env; recommend SOPS_AGE_RECIPIENTS for public template
    age: "${SOPS_AGE_RECIPIENTS}"
    # Optional providers (set to empty when not used)
    kms: "${SOPS_AWS_KMS_ARN:-}"
    gcp_kms: "${SOPS_GCP_KMS_RESOURCE_ID:-}"
    azure_keyvault: "${SOPS_AZURE_KEY_VAULT:-}"
