packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/expo': 1.3.25
  '@tailwindcss/postcss': 4.1.14
  '@tanstack/react-query': ^5.90.2
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  better-auth: 1.3.25
  nativewind: ^5.0.0-preview.1
  postcss: ^8.5.6
  react-native-reanimated: 4.1.2
  react-native-worklets: 0.6.0
  react-native-css: ^3.0.0-preview.5
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tailwindcss-safe-area: ^1.1.0
  tamagui: ^1.130.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  zod: ^3.25.49

catalogs:
  react19:
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native-renderer: 19.1.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
