packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/expo": 1.4.0-beta.9
  "@better-auth/cli": 1.4.0-beta.9
  "@tailwindcss/postcss": ^4.1.14
  "@tanstack/react-form": ^1.23.7
  "@tanstack/react-query": ^5.90.2
  "@trpc/client": ^11.6.0
  "@trpc/server": ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  better-auth: 1.4.0-beta.9
  tailwindcss: ^4.1.14
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native-renderer: 19.1.0

linkWorkspacePackages: true

nodeLinker: hoisted

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
