packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  # Auth
  "@better-auth/expo": 1.2.9
  "better-auth": 1.2.9

  "tamagui": ^1.130.8

  # Dev tooling
  tailwindcss: ^3.4.17
  tailwind-merge: ^3.3.0
  typescript: ^5.8.3
  zod: ^3.25.49
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
