packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@better-auth/expo": 1.3.8
  "better-auth": 1.3.8

  "tamagui": ^1.130.8

  # Dev tooling
  tailwindcss: ^3.4.17
  tailwind-merge: ^3.3.0
  typescript: ^5.9.2
  zod: ^3.25.49
  "@tanstack/react-query": ^5.87.1
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

nodeLinker: hoisted
linkWorkspacePackages: true
