# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - replace-me # Replace with your production branch, e.g., "main" or "master"
env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
  SOPS_KMS_KEY: ${{ secrets.SOPS_KMS_KEY }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "validating env vars"
          echo "Using SOPS for envs (AGE or KMS)"
          flyctl deploy --config apps/nextjs/fly.toml --dockerfile apps/nextjs/Dockerfile --build-arg SOPS_KMS_KEY="$SOPS_KMS_KEY" -e SOPS_AGE_KEY="$SOPS_AGE_KEY" -e SOPS_KMS_KEY="$SOPS_KMS_KEY"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
          SOPS_KMS_KEY: ${{ secrets.SOPS_KMS_KEY }}
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
  deploy-python:
    name: Deploy python api
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "validating env vars"
          echo "Using SOPS for envs (AGE or KMS)"
          flyctl deploy --config apps/travel-assistant-api/fly.toml --dockerfile apps/travel-assistant-api/Dockerfile --build-arg SOPS_KMS_KEY="$SOPS_KMS_KEY" -e SOPS_AGE_KEY="$SOPS_AGE_KEY" -e SOPS_KMS_KEY="$SOPS_KMS_KEY"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
          SOPS_KMS_KEY: ${{ secrets.SOPS_KMS_KEY }}
      # Optional: Uncomment the following lines to set up a tmate session for debugging if the deployment fails
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
